language: shell

os:
  - linux
  - osx
  - windows

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"
  matrix:
    - JDK="adopt@1.11.0-6"
    - JDK="adopt-openj9@1.11.0-6"
    - JDK="adopt@1.14.0-0"
    - JDK="adopt-openj9@1.14.0-0"

before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk

install:
  - java -version

script:
  - travis_retry ./gradlew test

before_cache:
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
