language: shell

os:
  - linux

env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - TERM="dumb"

before_install:
  - unzip jdk11_openj9_fix_v02.zip
  - export JAVA_HOME="$HOME/jdk11_openj9_fix_v02"
  - export PATH="jdk11_openj9_fix_v02/bin:$PATH"
install:
  - java -version

script:
  - travis_retry ./gradlew test

before_cache:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - $GRAVIS/clean-gradle-cache
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
